/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class SingleMode extends javax.swing.JFrame {
    Answer a = new Answer();
    /**
     * Creates new form SingleMode
     */
    public SingleMode() {
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(1024, 768));

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("RSU", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ลองทายคำศัพท์ดูสิ ..!");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 50, 371, 70);

        jButton1.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("B");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(630, 200, 60, 61);

        jButton2.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("C");
        jButton2.setToolTipText("");
        jPanel2.add(jButton2);
        jButton2.setBounds(720, 200, 60, 61);

        jButton3.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("D");
        jButton3.setToolTipText("");
        jPanel2.add(jButton3);
        jButton3.setBounds(810, 200, 60, 61);

        jButton4.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("E");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(900, 200, 60, 61);

        jButton5.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("F");
        jButton5.setToolTipText("");
        jPanel2.add(jButton5);
        jButton5.setBounds(540, 290, 60, 61);

        jButton6.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 51, 51));
        jButton6.setText("A");
        jButton6.setToolTipText("");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(540, 200, 60, 61);

        jButton7.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 51, 51));
        jButton7.setText("H");
        jButton7.setToolTipText("");
        jPanel2.add(jButton7);
        jButton7.setBounds(720, 290, 60, 61);

        jButton8.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("G");
        jButton8.setToolTipText("");
        jPanel2.add(jButton8);
        jButton8.setBounds(630, 290, 60, 61);

        jButton9.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(51, 51, 51));
        jButton9.setText("I");
        jButton9.setToolTipText("");
        jPanel2.add(jButton9);
        jButton9.setBounds(810, 290, 60, 61);

        jButton10.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("K");
        jButton10.setToolTipText("");
        jPanel2.add(jButton10);
        jButton10.setBounds(540, 380, 60, 61);

        jButton11.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton11.setForeground(new java.awt.Color(51, 51, 51));
        jButton11.setText("L");
        jButton11.setToolTipText("");
        jPanel2.add(jButton11);
        jButton11.setBounds(630, 380, 60, 61);

        jButton12.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton12.setForeground(new java.awt.Color(51, 51, 51));
        jButton12.setText("M");
        jButton12.setToolTipText("");
        jPanel2.add(jButton12);
        jButton12.setBounds(720, 380, 60, 61);

        jButton13.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton13.setForeground(new java.awt.Color(51, 51, 51));
        jButton13.setText("P");
        jButton13.setToolTipText("");
        jPanel2.add(jButton13);
        jButton13.setBounds(540, 470, 60, 61);

        jButton14.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton14.setForeground(new java.awt.Color(51, 51, 51));
        jButton14.setText("J");
        jButton14.setToolTipText("");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);
        jButton14.setBounds(900, 290, 60, 61);

        jButton15.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton15.setForeground(new java.awt.Color(51, 51, 51));
        jButton15.setText("O");
        jButton15.setToolTipText("");
        jPanel2.add(jButton15);
        jButton15.setBounds(900, 380, 60, 61);

        jButton16.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton16.setForeground(new java.awt.Color(51, 51, 51));
        jButton16.setText("Q");
        jButton16.setToolTipText("");
        jPanel2.add(jButton16);
        jButton16.setBounds(630, 470, 60, 61);

        jButton17.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton17.setForeground(new java.awt.Color(51, 51, 51));
        jButton17.setText("T");
        jButton17.setToolTipText("");
        jPanel2.add(jButton17);
        jButton17.setBounds(900, 470, 60, 61);

        jButton18.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton18.setForeground(new java.awt.Color(51, 51, 51));
        jButton18.setText("N");
        jButton18.setToolTipText("");
        jPanel2.add(jButton18);
        jButton18.setBounds(810, 380, 60, 61);

        jButton19.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton19.setForeground(new java.awt.Color(51, 51, 51));
        jButton19.setText("S");
        jButton19.setToolTipText("");
        jPanel2.add(jButton19);
        jButton19.setBounds(810, 470, 60, 61);

        jButton20.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton20.setForeground(new java.awt.Color(51, 51, 51));
        jButton20.setText("R");
        jButton20.setToolTipText("");
        jPanel2.add(jButton20);
        jButton20.setBounds(720, 470, 60, 61);

        jButton21.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton21.setForeground(new java.awt.Color(51, 51, 51));
        jButton21.setText("Y");
        jButton21.setToolTipText("");
        jPanel2.add(jButton21);
        jButton21.setBounds(900, 560, 60, 61);

        jButton22.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton22.setForeground(new java.awt.Color(51, 51, 51));
        jButton22.setText("Z");
        jButton22.setToolTipText("");
        jPanel2.add(jButton22);
        jButton22.setBounds(540, 650, 60, 61);

        jButton23.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton23.setForeground(new java.awt.Color(51, 51, 51));
        jButton23.setText("V");
        jButton23.setToolTipText("");
        jPanel2.add(jButton23);
        jButton23.setBounds(630, 560, 60, 61);

        jButton24.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton24.setForeground(new java.awt.Color(51, 51, 51));
        jButton24.setText("W");
        jButton24.setToolTipText("");
        jPanel2.add(jButton24);
        jButton24.setBounds(720, 560, 60, 61);

        jButton25.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton25.setForeground(new java.awt.Color(51, 51, 51));
        jButton25.setText("X");
        jButton25.setToolTipText("");
        jPanel2.add(jButton25);
        jButton25.setBounds(810, 560, 60, 61);

        jButton26.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jButton26.setForeground(new java.awt.Color(51, 51, 51));
        jButton26.setText("U");
        jButton26.setToolTipText("");
        jPanel2.add(jButton26);
        jButton26.setBounds(540, 560, 60, 61);

        jPanel1.setToolTipText("");
        jPanel1.setDoubleBuffered(false);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 8));

        jLabel4.setBackground(new java.awt.Color(255, 36, 168));
        jLabel4.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("____");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4);

        jLabel7.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("____");
        jPanel1.add(jLabel7);

        jLabel5.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("____");
        jPanel1.add(jLabel5);

        jLabel11.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("____");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11);

        jLabel8.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("____");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8);

        jLabel10.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("____");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10);

        jLabel12.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("____");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12);

        jLabel13.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("____");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("____");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14);

        jLabel15.setFont(new java.awt.Font("RSU", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("____");
        jLabel15.setToolTipText("");
        jPanel1.add(jLabel15);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(450, 20, 570, 180);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p1.jpg"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(0, 0, 1200, 750);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        new Answer().setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SingleMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SingleMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SingleMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SingleMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SingleMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
